M48
; DRILL file {KiCad (7.0.0)} date Thu Apr 20 13:17:39 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-20T13:17:39-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X6.0836Y-4.6878
X6.2568Y-4.6878
T2
X4.1Y-2.3
X4.1Y-4.7
X7.4Y-3.5
T0
M30
